// src/client/src/components/MessageInput.tsx
import React, { useState, useRef, useEffect } from 'react';

interface MessageInputProps {
  onSendMessage: (message: string) => void;
  onTyping: (isTyping: boolean) => void;
  disabled?: boolean;
  theme?: 'light' | 'dark';
  placeholder?: string;
}

const MessageInput: React.FC<MessageInputProps> = ({
  onSendMessage,
  onTyping,
  disabled = false,
  theme = 'light',
  placeholder = 'Type a message...',
}) => {
  const [message, setMessage] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const typingTimeoutRef = useRef<NodeJS.Timeout>();

  // Auto-resize textarea
  useEffect(() => {
    if (textareaRef.current) {
      textareaRef.current.style.height = 'auto';
      textareaRef.current.style.height = `${Math.min(textareaRef.current.scrollHeight, 120)}px`;
    }
  }, [message]);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!message.trim() || disabled) return;

    onSendMessage(message.trim());
    setMessage('');
    handleTypingStop();
  };

  const handleKeyPress = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSubmit(e);
    }
  };

  const handleInputChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    setMessage(e.target.value);
    handleTypingStart();
  };

  const handleTypingStart = () => {
    if (!isTyping) {
      setIsTyping(true);
      onTyping(true);
    }

    // Clear existing timeout
    if (typingTimeoutRef.current) {
      clearTimeout(typingTimeoutRef.current);
    }

    // Set new timeout to stop typing indicator
    typingTimeoutRef.current = setTimeout(() => {
      handleTypingStop();
    }, 3000);
  };

  const handleTypingStop = () => {
    if (isTyping) {
      setIsTyping(false);
      onTyping(false);
    }

    if (typingTimeoutRef.current) {
      clearTimeout(typingTimeoutRef.current);
    }
  };

  // Cleanup timeout on unmount
  useEffect(() => {
    return () => {
      if (typingTimeoutRef.current) {
        clearTimeout(typingTimeoutRef.current);
      }
    };
  }, []);

  return (
    <div className={`
      border-t p-4
      ${theme === 'dark' 
        ? 'bg-gray-800 border-gray-700' 
        : 'bg-white border-gray-200'
      }
    `}>
      <form onSubmit={handleSubmit} className="flex items-end space-x-2">
        <div className="flex-1 relative">
          <textarea
            ref={textareaRef}
            value={message}
            onChange={handleInputChange}
            onKeyPress={handleKeyPress}
            placeholder={placeholder}
            disabled={disabled}
            rows={1}
            className={`
              w-full px-3 py-2 border rounded-lg resize-none
              focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent
              ${theme === 'dark' 
                ? 'bg-gray-700 border-gray-600 text-white placeholder-gray-400' 
                : 'bg-white border-gray-300 text-gray-900 placeholder-gray-500'
              }
              ${disabled ? 'opacity-50 cursor-not-allowed' : ''}
            `}
            style={{ maxHeight: '120px', minHeight: '40px' }}
          />
          
          {/* Character count (if needed) */}
          {message.length > 1800 && (
            <div className={`
              absolute bottom-1 right-2 text-xs
              ${message.length > 2000 ? 'text-red-500' : 'text-yellow-500'}
            `}>
              {message.length}/2000
            </div>
          )}
        </div>

        <button
          type="submit"
          disabled={disabled || !message.trim()}
          className={`
            p-2 rounded-lg transition-colors
            ${disabled || !message.trim()
              ? 'bg-gray-300 text-gray-500 cursor-not-allowed'
              : 'bg-blue-600 text-white hover:bg-blue-700'
            }
          `}
          aria-label="Send message"
        >
          {disabled ? (
            <div className="w-5 h-5 border-2 border-gray-400 border-t-transparent rounded-full animate-spin"></div>
          ) : (
            <svg
              className="w-5 h-5"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8"
              />
            </svg>
          )}
        </button>
      </form>

      {/* Quick Actions */}
      <div className="mt-2 flex flex-wrap gap-2">
        <button
          onClick={() => setMessage("I need help with a legal matter")}
          disabled={disabled}
          className={`
            px-3 py-1 text-xs rounded-full border transition-colors
            ${theme === 'dark' 
              ? 'border-gray-600 text-gray-300 hover:bg-gray-700' 
              : 'border-gray-300 text-gray-600 hover:bg-gray-50'
            }
            ${disabled ? 'opacity-50 cursor-not-allowed' : ''}
          `}
        >
          Legal Help
        </button>
        <button
          onClick={() => setMessage("I want to book a consultation")}
          disabled={disabled}
          className={`
            px-3 py-1 text-xs rounded-full border transition-colors
            ${theme === 'dark' 
              ? 'border-gray-600 text-gray-300 hover:bg-gray-700' 
              : 'border-gray-300 text-gray-600 hover:bg-gray-50'
            }
            ${disabled ? 'opacity-50 cursor-not-allowed' : ''}
          `}
        >
          Book Consultation
        </button>
        <button
          onClick={() => setMessage("What are your practice areas?")}
          disabled={disabled}
          className={`
            px-3 py-1 text-xs rounded-full border transition-colors
            ${theme === 'dark' 
              ? 'border-gray-600 text-gray-300 hover:bg-gray-700' 
              : 'border-gray-300 text-gray-600 hover:bg-gray-50'
            }
            ${disabled ? 'opacity-50 cursor-not-allowed' : ''}
          `}
        >
          Practice Areas
        </button>
      </div>
    </div>
  );
};

export default MessageInput;

// src/lib/components/MessageInput.svelte
<script lang="ts">
  interface Props {
    disabled?: boolean;
    theme?: 'light' | 'dark';
    placeholder?: string;
    onsend?: (message: string) => void;
  }

  let {
    disabled = false,
    theme = 'light',
    placeholder = 'Type your message...',
    onsend
  }: Props = $props();

  let message = $state('');
  let textArea: HTMLTextAreaElement;

  function handleSubmit() {
    if (message.trim() && !disabled) {
      onsend?.(message.trim());
      message = '';
      adjustHeight();
    }
  }
  
  function handleKeyDown(event: KeyboardEvent) {
    if (event.key === 'Enter' && !event.shiftKey) {
      event.preventDefault();
      handleSubmit();
    }
  }
  
  function adjustHeight() {
    if (textArea) {
      textArea.style.height = 'auto';
      textArea.style.height = Math.min(textArea.scrollHeight, 120) + 'px';
    }
  }
  
  $effect(() => {
    if (message) adjustHeight();
  });
</script>

<div class="p-4 border-t"
     class:border-gray-200={theme === 'light'}
     class:border-gray-700={theme === 'dark'}>
  <div class="flex space-x-2">
    <textarea
      bind:this={textArea}
      bind:value={message}
      onkeydown={handleKeyDown}
      oninput={adjustHeight}
      {placeholder}
      {disabled}
      rows="1"
      aria-label="Message input"
      class="flex-1 resize-none rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 border"
      class:bg-white={theme === 'light'}
      class:text-gray-900={theme === 'light'}
      class:border-gray-300={theme === 'light'}
      class:bg-gray-800={theme === 'dark'}
      class:text-gray-100={theme === 'dark'}
      class:border-gray-600={theme === 'dark'}
      style="max-height: 120px; overflow-y: auto;"
    ></textarea>
    
    <button
      onclick={handleSubmit}
      {disabled}
      aria-label="Send message"
      class="px-4 py-2 rounded-lg text-white font-medium transition-colors"
      class:bg-blue-600={!disabled}
      class:hover:bg-blue-700={!disabled}
      class:bg-gray-400={disabled}
      class:cursor-not-allowed={disabled}
    >
      <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width={2} d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8" />
      </svg>
    </button>
  </div>
</div>
